let max = 5;
let min = 2;

let playerName;

let secretNumber;
let guessedNumber;

//(max-min + 1) finds the total number of values generated. +1 is a constant
//we have to multiply Math.random with (max-min + 1) because it generates value from 0-1, including 0 but never 1 itself.
//+min ensures that the number generated by Math.random and (max-min + 1) will start from the miminum number set. This is usually used if minimum number is greater than 1.

do {

    playerName = prompt("What is your name? ");

    if (playerName === null)
    {
        alert("Aw, you canceled the game!");
    }   
    else if (playerName.trim() === "") {
        alert("No name, no game!");
    }
    else {

        secretNumber = Math.floor(Math.random() * (max-min + 1)) + min;

        do {
            guessedNumber = parseInt(prompt("Welcome, " + playerName + "! \n\nWhat do you think is the number I have for you? \nClue: It's between 1 and 10!"));
            
            switch (true) 
            {
                case guessedNumber < 0:
                    alert("I gave you a clue! That's way below the minimum number!");
                    break;
                case guessedNumber > 10:
                    alert("I gave you a clue! That's way above the maximum number!");
                    break;
                case guessedNumber < secretNumber:
                    alert("Your guess is lower than my number. Try again!");
                    break;
                case guessedNumber > secretNumber:
                    alert("Your guess is greater than my number. Nice try. Do it again!");
                    break;
                case guessedNumber === secretNumber:
                    alert("Congratulations! You guessed the correct number " + playerName + "! It is: " + secretNumber);
                    break;
            }
            } while(guessedNumber !== secretNumber);
    }

} while (playerName.trim() === "")



