// script.js

// Activity: Exploring Common JS Built-in Methods

// Objective: Practice using common JS built-in methods to perform various operations.

// Instructions:
// 1. Create an HTML file with a heading that says "Common JS Built-in Methods".
// 2. Create a JavaScript file and link it to the HTML file.
// 3. In the JavaScript file, you will find comments describing different tasks that need to be performed using common JS built-in methods. Your task is to write the code to complete these tasks.
// 4. The tasks to be completed are as follows:
//    a. Calculate the square root of a given number.
//    b. Generate a random number between 1 and 10.
//    c. Convert a string representation of a number to an actual number.
//    d. Check if a value is not a number.
//    e. Convert a number to a string.

// Note: Read the comments carefully to understand the requirements for each task. Use the appropriate method to accomplish the given task.

// Good luck!

// Your code implementation goes here:
// Calculate the square root of a given number

//asks a user input
const inputData = parseInt(prompt("Give me a number: "));

//formula for squaring a number
const square = inputData ** 2;

//print in the console
console.log(square);


// Generate a random number between 1 and 10
let max = 10;
let min = 1;

//(max-min + 1) finds the total number of values generated. +1 is a constant
//we have to multiply Math.random with (max-min + 1) because it generates value from 0-1, including 0 but never 1 itself.
//+min ensures that the number generated by Math.random and (max-min + 1) will start from the miminum number set. This is usually used if minimum number is greater than 1.
let random = Math.floor(Math.random() * (max-min + 1)) + min;

console.log(random);


// Convert a string representation of a number to an actual number
const stringNum = "12";
const convertedString = parseInt(stringNum);


// Check if a value is not a number
if(typeof convertedString === "number") {
    console.log(true);
} else {
    console.log(false);
}


// Convert a number to a string
const convertedNumber = convertedString.toString();

if(typeof convertedNumber === "number") {
    console.log(true);
} else {
    console.log(false);
}
